# Schema for the views plugins of the decoupled_auth module.
views.field.user_decoupled:
  type: views_field
  label: 'Decoupled'

views.filter.user_decoupled:
  type: views_filter
  label: 'Decoupled'
