name: 'Simple CRM Config'
description: 'Default configuration for the Simple CRM module.'
type: module
core: 8.x
dependencies:
  - decoupled_auth_crm
version: 8.x-1.x
features:
  required:
    - core.entity_form_display.profile.crm_indiv.default
    - core.entity_form_display.profile.crm_org.default
    - core.entity_view_display.profile.crm_indiv.default
    - core.entity_view_display.profile.crm_org.default
    - field.field.profile.crm_indiv.crm_address
    - field.field.profile.crm_indiv.crm_dob
    - field.field.profile.crm_indiv.crm_email
    - field.field.profile.crm_indiv.crm_gender
    - field.field.profile.crm_indiv.crm_name
    - field.field.profile.crm_org.crm_logo
    - field.field.profile.crm_org.crm_org_address
    - field.field.profile.crm_org.crm_org_email
    - field.field.profile.crm_org.crm_org_name
    - field.storage.profile.crm_address
    - field.storage.profile.crm_dob
    - field.storage.profile.crm_email
    - field.storage.profile.crm_gender
    - field.storage.profile.crm_logo
    - field.storage.profile.crm_name
    - field.storage.profile.crm_org_address
    - field.storage.profile.crm_org_email
    - field.storage.profile.crm_org_name
    - profile.type.crm_indiv
    - profile.type.crm_org
    - user.role.crm_indiv
    - user.role.crm_org
